### ISSUE TITLE
Unable to build repo

### ISSUE THREAD

**Issue by akhil-karanth** [census-instrumentation/opencensus-service#218]
I am trying to build the ocagent using the followign command as specified in the documentation

```
./build_binaries.sh binaries
```

I am getting the following error:

```# github.com/uber/tchannel-go/thrift/gen-go/meta
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:79:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:103:15: assignment mismatch: 2 variables but 1 values
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:152:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:176:15: assignment mismatch: 2 variables but 1 values
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:225:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:249:15: assignment mismatch: 2 variables but 1 values
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:295:31: cannot use metaProcessorHealth literal (type *metaProcessorHealth) as type thrift.TProcessorFunction in assignment:
	*metaProcessorHealth does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:296:34: cannot use metaProcessorThriftIDL literal (type *metaProcessorThriftIDL) as type thrift.TProcessorFunction in assignment:
	*metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:297:36: cannot use metaProcessorVersionInfo literal (type *metaProcessorVersionInfo) as type thrift.TProcessorFunction in assignment:
	*metaProcessorVersionInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:307:27: not enough arguments in call to processor.Process
	have (int32, thrift.TProtocol, thrift.TProtocol)
	want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:307:27: too many errors
```

Any way to get this to build. I am on the latest go version

Even simply trying to install the ocagent fails:

```
 github.com/uber/tchannel-go/thrift/gen-go/meta
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:79:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:103:15: assignment mismatch: 2 variables but 1 values
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:152:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:176:15: assignment mismatch: 2 variables but 1 values
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:225:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:249:15: assignment mismatch: 2 variables but 1 values
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:295:31: cannot use metaProcessorHealth literal (type *metaProcessorHealth) as type thrift.TProcessorFunction in assignment:
	*metaProcessorHealth does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:296:34: cannot use metaProcessorThriftIDL literal (type *metaProcessorThriftIDL) as type thrift.TProcessorFunction in assignment:
	*metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:297:36: cannot use metaProcessorVersionInfo literal (type *metaProcessorVersionInfo) as type thrift.TProcessorFunction in assignment:
	*metaProcessorVersionInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:307:27: not enough arguments in call to processor.Process
	have (int32, thrift.TProtocol, thrift.TProtocol)
	want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
../../uber/tchannel-go/thrift/gen-go/meta/meta.go:307:27: too many errors
```

**Comment by songy23** [comment]
Looks like a dependency issue introduced in https://github.com/census-instrumentation/opencensus-service/pull/184. /cc @pjanotti

**Comment by pjanotti** [comment]
@akhil-karanth we use go 1.11 and go mod, could check the brief nodes at https://github.com/census-instrumentation/opencensus-service/blob/master/CONTRIBUTING.md#general-notes

**Comment by akhil-karanth** [comment]
@pjanotti Thank you! i was missing setting the GO111MODULE=on

**Comment by odeke-em** [comment]
>Can we make our makefile to set this environment variable?

@bogdandrutu they also need Go1.11 too. @songy23 is currently making an update to the README in #247
